export default [
  {
    pillar: "Support",
    product: [
      {
        name: "Supply Chain Operations Tool (GSCOPE) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "OAR ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Supply Chain Support Engineering ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Operational Data Store (ODS) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
    ],
  },
  {
    pillar: "Enterprise Item and Inventory",
    product: [
      {
        name: "Content Acquisition",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
    ],
  },
  {
    pillar: "Fulfillment",
    product: [
      {
        name: "Fulfillment Management Services ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Returns Management (RMS) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "FC Systems (Future Product) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },

      {
        name: "Returns Management (RMS) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Fulfillment Optimization - Smart Sourcing ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },

      {
        name: "GLS Classic ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
    ],
  },
  {
    pillar: "Marketplace",
    product: [
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Cross Border Trade ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
    ],
  },
  {
    pillar: "Stores and Associates",
    product: [
      {
        name: "Outbound Processing ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Fresh Production ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Store Financials ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Store Inventory Management ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
    ],
  },
  // {
  //   pillar: "Enterprise Item and Inventory",
  //   product: [
  //     "Content Acquisition",
  //     "Inventory Management (IMS) ",
  //     "Supply Chain Item Management (LIMO)",
  //     "Enterprise Inventory ",
  //     "Tick Tick ",
  //     "ConGO",
  //     "Partner & Location Catalog",
  //     "Catalog",
  //     "Partner Experience ",
  //     "Operational Tools",
  //     "MT Operations",
  //     "Merchant Experience ",
  //     "Advanced Ship Notice (ASN) Visibility",
  //     "Wakanda (Unified Inventory) ",
  //     "iAnalytics",
  //     "Catalog – Setup Pipeline ",
  //     "Catalog – Data Sciences ",
  //     "CASTAR",
  //     "Supplier Expereince ",
  //     "Site Serving ",
  //     "RETINA ",
  //     "Item Setup ",
  //     "Uber Store ",
  //     "EXPERT ",
  //     "Cost RT ",
  //     "JET KEPLER (NON-CTO) ",
  //   ],
  // },
  // {
  //   pillar: "Fulfillment",
  //   product: [
  //     "Fulfillment Management Services ",
  //     "Catalog Tools ",
  //     "Current Backend (C-OMS, Payments, Emails, Order Migration) ",
  //     "eCommerce: Transactions: GeC Pangaea Communications ",
  //     "Fulfillment Optimization - Smart Sourcing ",
  //     "Returns Management (RMS) ",
  //     "Customer Service (CCA) ",
  //     "FC Systems (Future Product) ",
  //     "Partner Integration (Bedrock, NGBedrock, Partner Onboarding) ",
  //     "GLS Classic ",
  //     "Fulfillment Order Manager ",
  //     "Fulfillment Audit, Staging & Loading ",
  //     "Fulfillment BI ",
  //     "Fulfillment Foundation Services ",
  //     "Fulfillment Order Services ",
  //     "Fulfillment Picklist Optimization ",
  //     "Fulfillment Dashboard & Reporting ",
  //     "Fulfillment Picking ",
  //     "Fulfillment Dispense ",
  //     "Muse ",
  //     "Fulfillment Order Processor ",
  //     "Supply Chain Implementation Lifecycle Solutions ",
  //     "Food Safety Provenance Tracker (Blockchain) ",
  //     "GLS NextGen ",
  //     "Fulfillment Packing ",
  //     "Fulfillment - Store Dev Ops ",
  //     "Global Integrated Fulfillment (GIF) ",
  //     "Catalyst WMS ",
  //     "SCT Customer Recovery ",
  //     "CP-Warehouse Management Product ",
  //     "Walmart Fulfillment Services ",
  //     "Supply Chain Tracker ",
  //     "OMS Comms ",
  //     "Sales Order ",
  //     "OMS Accounting ",
  //     "Order Services ",
  //     "Pulse ",
  //     "Centurions ",
  //     "Pickpath Optimization Platform ",
  //     "Store Configuration and Slot Scheduling ",
  //     "OMS ",
  //     "Concorde ",
  //     "Blockchain Platforms ",
  //     "One Walmart ",
  //     "Omni-Channel Fulfillment (Commercialization) ",
  //     "Supplier Quality Excellence ",
  //     "EndGame Automated Outbound WMS ",
  //     "Thor WMS ",
  //     "Hawkeye ",
  //     "Schaefer Support Tools ",
  //   ],
  // },
  // {
  //   pillar: "Marketplace",
  //   product: [
  //     "Cross Border Trade ",
  //     "Marketplace Services ",
  //     "Marketplace Platforms ",
  //     "Marketplace Seller Experience ",
  //     "Marketplace Communication ",
  //     "MP Operations ",
  //     "Marketplace Analytics ",
  //     "Inventory Audits ",
  //   ],
  // },
  // {
  //   pillar: "Stores and Associates",
  //   product: [
  //     "Outbound Processing ",
  //     "Fresh Production ",
  //     "Store Financials ",
  //     "Store Inventory Management ",
  //     "Inbound Processing ",
  //     "Location Services ",
  //     "Store Foundational Services ",
  //     "Integrated Returns ",
  //     "Price Execution ",
  //     "Technical Services ",
  //     "Rapid Response ",
  //     "Signs and Labels ",
  //     "Store_Club Operational Metrics & Tools ",
  //     "Innovation Services ",
  //     "Integrated Check-In ",
  //     "Store_Club Comm & Task Planning ",
  //     "Store_Club Item & Tax ",
  //     "Enhanced Revenue Recognition (ERR) ",
  //     "Workforce Management ",
  //     "Store Academy ",
  //     "Asset Protection ",
  //     "Auto-C ",
  //     "Trace App ",
  //     "AE Architecture ",
  //     "Sensor Technology ",
  //     "STR ZEUS ",
  //     "ATMT ",
  //     "Store Mobility Directed Voice ",
  //     "PTT (Mark1) ",
  //     "Store Mobility - Voice ",
  //     "Knowledge Graph ",
  //     "SRE Store Systems Operations ",
  //     "Store Systems Data Platform ",
  //     "Store Systems Mobile Platform ",
  //     "ASPARK ",
  //     "All Spark ",
  //     "WM Hosted Bossa Nova Azure Subscription ",
  //     "Sumo ",
  //     "Stock Financial Transfers (SFT) ",
  //     "Store Systems Platform Services ",
  //     "Store Systems Technical Support ",
  //     "Store Systems Devops ",
  //     "AI Support Dev ",
  //     "GWFM Analytics ",
  //     "GWFM Budget & Demand ",
  //     "GWFM Platforms ",
  //     "GWFM Scheduling ",
  //     "DirectME ",
  //     "TaskIT ",
  //     "SARO ",
  //     "Item Information ",
  //     "Daily availability ",
  //     "SIA ",
  //     "Vizpick ",
  //     "Pinpoint ",
  //     "Shelf Availability ",
  //     "RFID ",
  //     "MeW Subgraphs & Data Services ",
  //     "Athena Federation Gateway ",
  //     "Project Diamond ",
  //     "OSCA (NON-CTO) ",
  //   ],
  // },
  // {
  //   pillar: "Support",
  //   product: [
  //     "Supply Chain Operations Tool (GSCOPE) ",
  //     "OAR ",
  //     "Supply Chain Support Engineering ",
  //     "Operational Data Store (ODS) ",
  //     "CSIS-DevOps & Cloud Engineering ",
  //   ],
  // },
  // // Omni Supply Chain System ( OSCS ) Devops Dashboard
  // {
  //   pillar: "Transportation Services",
  //   product: [
  //     "Shipment and Tracking Platform ",
  //     "Last Mile Services ",
  //     "Fleet Management ",
  //     "Transportation ",
  //     "Yard Management ",
  //     "Inbound Appt Scheduler ",
  //     "SCT Sortation ",
  //     "Planning and Optimization ",
  //     "Transportation Master Data ",
  //     "SWARM (E2E Network Optimizer) ",
  //     "Driver Experience ",
  //     "Shipment Request ",
  //     "SCT Delivery Acceleration ",
  //     "LOBO – Label Generation ",
  //     "Checkin ",
  //     "ETA ",
  //     "Mobius ",
  //     "Ether ",
  //     "Resource Allocation ",
  //     "Cartonisation ",
  //     "Optimizer As A Service ",
  //     "Inbound Optimization ",
  //     "STRIDE ",
  //     "CSIS - In Home ",
  //     "CSIS - Smart Reordering ",
  //     "Walmart Mission Control ",
  //     "DCC (Distributor Carrier Configuration) ",
  //     "CONVERSATIONAL COMMERCE ",
  //     "INHOME ",
  //     "SMART REORDER ",
  //     "WELLNESS ",
  //     "NPI CORE SERVICES ",
  //   ],
  // },
];

// =================

//   pillar: "Support",
//   product: [
//     {
//       name: "Supply Chain Operations Tool (GSCOPE)",
//       applications: [
//         {
//           name: "application",
//           tools: [{ nameOfTool: "tool", toolData: ["tool information"] }],
//         },
//         {
//           name: "application",
//           tools: [{ nameOfTool: "tool", toolData: ["tool information"] }],
//         },
//         {
//           name: "application",
//           tools: [{ nameOfTool: "tool", toolData: ["tool information"] }],
//         },
//       ],
//     },
//   ],
// },
// {
