export default [
  {
    pillar: "Support",
    product: [
      {
        name: "Supply Chain Operations Tool (GSCOPE) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "OAR ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Supply Chain Support Engineering ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Operational Data Store (ODS) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
    ],
  },
  {
    pillar: "Enterprise Item and Inventory",
    product: [
      {
        name: "Supply Chain Operations Tool (GSCOPE) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "OAR ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Supply Chain Support Engineering ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Operational Data Store (ODS) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
    ],
  },
  {
    pillar: "Fulfillment",
    product: [
      {
        name: "Supply Chain Operations Tool (GSCOPE) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "OAR ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Supply Chain Support Engineering ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Operational Data Store (ODS) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
    ],
  },
  {
    pillar: "Marketplace",
    product: [
      {
        name: "Supply Chain Operations Tool (GSCOPE) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "OAR ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Supply Chain Support Engineering ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Operational Data Store (ODS) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
    ],
  },
  {
    pillar: "Stores and Associates",
    product: [
      {
        name: "Supply Chain Operations Tool (GSCOPE) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "OAR ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Supply Chain Support Engineering ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
      {
        name: "Operational Data Store (ODS) ",
        applications: [
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
          { name: "application", tools: ["tool1", "tool2", "tool3"] },
        ],
      },
    ],
  },
];
