export default [
  {
    pillar: "Support",
    product: [
      {
        name: "Supply111 ",
        application: [
          {
            name: "application",
            tools: [
              {
                toolName: "header",
                toolsList: ["Mvzxcvz1", "Revzxy1", "Lncbv1"],
              },
              {
                toolName: "footer",
                toolsList: ["Mamvvbr2", "bxcvitory2", "Libvck2"],
              },
              {
                toolName: "blog",
                toolsList: ["Mavge3", "Redastrory3", "Linkhhh3"],
              },
            ],
          },
          {
            name: "Github",
            tools: [
              {
                toolName: "hhdgfhd",
                toolsList: ["Mana7446ger4", "Rep89y4", "Linfadsk4"],
              },
              {
                toolName: "fhgfhdfghd",
                toolsList: ["fadsfa5", "Repofay5", "fads5"],
              },
              {
                toolName: "gsfdgsgsdfg",
                toolsList: ["Majfhr6", "Rephlkjhlry6", "Llhkjh6"],
              },
            ],
          },
          {
            name: "Facebook",
            tools: [
              {
                toolName: "jhjfhjfhg2",
                toolsList: ["Mhgdfhdr7", "Repjfhgfry7", "Ljfgh7"],
              },
              {
                toolName: "foo4524522542",
                toolsList: ["Mkjjfhger8", "Reetryerty8", "Lyetk8"],
              },
              {
                toolName: "hdgfhdfghh2",
                toolsList: ["M25345er9", "Repdhfgdy9", "hgd9"],
              },
            ],
          },
        ],
      },

      {
        name: "(GSCOPE)222",
        application: [
          {
            name: "hello world",
            tools: [
              {
                toolName: "gsfdgsdfg",
                toolsList: ["kjhgkghjkgh1", "Repjfhgjfg1", "Lijfhgjfgh1"],
              },
              {
                toolName: "foogdfhster",
                toolsList: [
                  "Managerjhgjfghj2",
                  "Repositoryjfghjfhg2",
                  "Lijfhgjfnk2",
                ],
              },
              {
                toolName: "blgfdog",
                toolsList: ["Managbvxe3", "Repfgsfdository3", "Ljfhgjkink3"],
              },
            ],
          },
          {
            name: "Google",
            tools: [
              {
                toolName: "headfdaer1",
                toolsList: ["Manager4", "Repository4", "Link4"],
              },
              {
                toolName: "footegsfdhr1",
                toolsList: ["Manager5", "Repository5", "Lin5"],
              },
              {
                toolName: "blohggsfdg1",
                toolsList: ["Manager6", "Repository6", "Link6"],
              },
            ],
          },
          {
            name: "Amazon",
            tools: [
              {
                toolName: "heagdfsgder2",
                toolsList: ["Manadfgger7", "Repodhgfhsitory7", "Lihdfgnk7"],
              },
              {
                toolName: "footgsfdgser2",
                toolsList: ["Manahdfghdger8", "Rephdfghdository8", "Linhdfgk8"],
              },
              {
                toolName: "blogsfdgg2",
                toolsList: ["Manahdgfhger9", "Rejfjdpository9", "Lihdgfhdnk9"],
              },
            ],
          },
        ],
      },

      {
        name: "Tools333",
        application: [
          {
            name: "afadsf",
            tools: [
              {
                toolName: "hehghdghdader",
                toolsList: ["gfsdsg", "gfgsfgsfg", "gsfhsdhs1"],
              },
              {
                toolName: "footer",
                toolsList: ["fadsfafa2", "fasdfa2", "sgfds2"],
              },
              {
                toolName: "blog",
                toolsList: ["gsdfsgfd3", "fadasf3", "afdsfasdf3"],
              },
            ],
          },
          {
            name: "fasdf",
            tools: [
              {
                toolName: "headgsdfgdr1",
                toolsList: ["gsdfgsfg4", "fadsafda4", "fdsagasfad4"],
              },
              {
                toolName: "foothghder1",
                toolsList: ["gsdfgs5", "afdsfasdf5", "gsfdgsgsd5"],
              },
              {
                toolName: "blohdfghg1",
                toolsList: ["hdfghdgfh6", "kgjhgkkj6", "gsdfgsdfg6"],
              },
            ],
          },
          {
            name: "tretwewet",
            tools: [
              {
                toolName: "heahdfgdder2",
                toolsList: ["tryrtyerty7", "twertwwter7", "iyuuyiuyityui7"],
              },
              {
                toolName: "foojhgjfter2",
                toolsList: ["gsdfshsdhs8", "jhgfjhjgj8", "dsagaffhfg8"],
              },
              {
                toolName: "blojfhgfjg2",
                toolsList: ["gsfdhssdh9", "twretwtwert9", "jfhgjfjhhjgfgjh9"],
              },
            ],
          },
        ],
      },
    ],
  },

  //     {
  //       name: "OAR ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application44", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Supply Chain Support Engineering ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application55", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Operational Data Store (ODS) ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application66", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   pillar: "Enterprise Item and Inventory",
  //   product: [
  //     {
  //       name: "Content Acquisition",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   pillar: "Fulfillment",
  //   product: [
  //     {
  //       name: "Fulfillment Management Services ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Returns Management (RMS) ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "FC Systems (Future Product) ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },

  //     {
  //       name: "Returns Management (RMS) ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Fulfillment Optimization - Smart Sourcing ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },

  //     {
  //       name: "GLS Classic ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "ahmed3", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   pillar: "Marketplace",
  //   product: [
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Cross Border Trade ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   pillar: "Stores and Associates",
  //   product: [
  //     {
  //       name: "Outbound Processing ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Fresh Production ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Store Financials ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //     {
  //       name: "Store Inventory Management ",
  //       applications: [
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //         { name: "application", tools: ["tool1", "tool2", "tool3"] },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   pillar: "Enterprise Item and Inventory",
  //   product: [
  //     "Content Acquisition",
  //     "Inventory Management (IMS) ",
  //     "Supply Chain Item Management (LIMO)",
  //     "Enterprise Inventory ",
  //     "Tick Tick ",
  //     "ConGO",
  //     "Partner & Location Catalog",
  //     "Catalog",
  //     "Partner Experience ",
  //     "Operational Tools",
  //     "MT Operations",
  //     "Merchant Experience ",
  //     "Advanced Ship Notice (ASN) Visibility",
  //     "Wakanda (Unified Inventory) ",
  //     "iAnalytics",
  //     "Catalog – Setup Pipeline ",
  //     "Catalog – Data Sciences ",
  //     "CASTAR",
  //     "Supplier Expereince ",
  //     "Site Serving ",
  //     "RETINA ",
  //     "Item Setup ",
  //     "Uber Store ",
  //     "EXPERT ",
  //     "Cost RT ",
  //     "JET KEPLER (NON-CTO) ",
  //   ],
  // },
  // {
  //   pillar: "Fulfillment",
  //   product: [
  //     "Fulfillment Management Services ",
  //     "Catalog Tools ",
  //     "Current Backend (C-OMS, Payments, Emails, Order Migration) ",
  //     "eCommerce: Transactions: GeC Pangaea Communications ",
  //     "Fulfillment Optimization - Smart Sourcing ",
  //     "Returns Management (RMS) ",
  //     "Customer Service (CCA) ",
  //     "FC Systems (Future Product) ",
  //     "Partner Integration (Bedrock, NGBedrock, Partner Onboarding) ",
  //     "GLS Classic ",
  //     "Fulfillment Order Manager ",
  //     "Fulfillment Audit, Staging & Loading ",
  //     "Fulfillment BI ",
  //     "Fulfillment Foundation Services ",
  //     "Fulfillment Order Services ",
  //     "Fulfillment Picklist Optimization ",
  //     "Fulfillment Dashboard & Reporting ",
  //     "Fulfillment Picking ",
  //     "Fulfillment Dispense ",
  //     "Muse ",
  //     "Fulfillment Order Processor ",
  //     "Supply Chain Implementation Lifecycle Solutions ",
  //     "Food Safety Provenance Tracker (Blockchain) ",
  //     "GLS NextGen ",
  //     "Fulfillment Packing ",
  //     "Fulfillment - Store Dev Ops ",
  //     "Global Integrated Fulfillment (GIF) ",
  //     "Catalyst WMS ",
  //     "SCT Customer Recovery ",
  //     "CP-Warehouse Management Product ",
  //     "Walmart Fulfillment Services ",
  //     "Supply Chain Tracker ",
  //     "OMS Comms ",
  //     "Sales Order ",
  //     "OMS Accounting ",
  //     "Order Services ",
  //     "Pulse ",
  //     "Centurions ",
  //     "Pickpath Optimization Platform ",
  //     "Store Configuration and Slot Scheduling ",
  //     "OMS ",
  //     "Concorde ",
  //     "Blockchain Platforms ",
  //     "One Walmart ",
  //     "Omni-Channel Fulfillment (Commercialization) ",
  //     "Supplier Quality Excellence ",
  //     "EndGame Automated Outbound WMS ",
  //     "Thor WMS ",
  //     "Hawkeye ",
  //     "Schaefer Support Tools ",
  //   ],
  // },
  // {
  //   pillar: "Marketplace",
  //   product: [
  //     "Cross Border Trade ",
  //     "Marketplace Services ",
  //     "Marketplace Platforms ",
  //     "Marketplace Seller Experience ",
  //     "Marketplace Communication ",
  //     "MP Operations ",
  //     "Marketplace Analytics ",
  //     "Inventory Audits ",
  //   ],
  // },
  // {
  //   pillar: "Stores and Associates",
  //   product: [
  //     "Outbound Processing ",
  //     "Fresh Production ",
  //     "Store Financials ",
  //     "Store Inventory Management ",
  //     "Inbound Processing ",
  //     "Location Services ",
  //     "Store Foundational Services ",
  //     "Integrated Returns ",
  //     "Price Execution ",
  //     "Technical Services ",
  //     "Rapid Response ",
  //     "Signs and Labels ",
  //     "Store_Club Operational Metrics & Tools ",
  //     "Innovation Services ",
  //     "Integrated Check-In ",
  //     "Store_Club Comm & Task Planning ",
  //     "Store_Club Item & Tax ",
  //     "Enhanced Revenue Recognition (ERR) ",
  //     "Workforce Management ",
  //     "Store Academy ",
  //     "Asset Protection ",
  //     "Auto-C ",
  //     "Trace App ",
  //     "AE Architecture ",
  //     "Sensor Technology ",
  //     "STR ZEUS ",
  //     "ATMT ",
  //     "Store Mobility Directed Voice ",
  //     "PTT (Mark1) ",
  //     "Store Mobility - Voice ",
  //     "Knowledge Graph ",
  //     "SRE Store Systems Operations ",
  //     "Store Systems Data Platform ",
  //     "Store Systems Mobile Platform ",
  //     "ASPARK ",
  //     "All Spark ",
  //     "WM Hosted Bossa Nova Azure Subscription ",
  //     "Sumo ",
  //     "Stock Financial Transfers (SFT) ",
  //     "Store Systems Platform Services ",
  //     "Store Systems Technical Support ",
  //     "Store Systems Devops ",
  //     "AI Support Dev ",
  //     "GWFM Analytics ",
  //     "GWFM Budget & Demand ",
  //     "GWFM Platforms ",
  //     "GWFM Scheduling ",
  //     "DirectME ",
  //     "TaskIT ",
  //     "SARO ",
  //     "Item Information ",
  //     "Daily availability ",
  //     "SIA ",
  //     "Vizpick ",
  //     "Pinpoint ",
  //     "Shelf Availability ",
  //     "RFID ",
  //     "MeW Subgraphs & Data Services ",
  //     "Athena Federation Gateway ",
  //     "Project Diamond ",
  //     "OSCA (NON-CTO) ",
  //   ],
  // },
  // {
  //   pillar: "Support",
  //   product: [
  //     "Supply Chain Operations Tool (GSCOPE) ",
  //     "OAR ",
  //     "Supply Chain Support Engineering ",
  //     "Operational Data Store (ODS) ",
  //     "CSIS-DevOps & Cloud Engineering ",
  //   ],
  // },
  // // Omni Supply Chain System ( OSCS ) Devops Dashboard
  // {
  //   pillar: "Transportation Services",
  //   product: [
  //     "Shipment and Tracking Platform ",
  //     "Last Mile Services ",
  //     "Fleet Management ",
  //     "Transportation ",
  //     "Yard Management ",
  //     "Inbound Appt Scheduler ",
  //     "SCT Sortation ",
  //     "Planning and Optimization ",
  //     "Transportation Master Data ",
  //     "SWARM (E2E Network Optimizer) ",
  //     "Driver Experience ",
  //     "Shipment Request ",
  //     "SCT Delivery Acceleration ",
  //     "LOBO – Label Generation ",
  //     "Checkin ",
  //     "ETA ",
  //     "Mobius ",
  //     "Ether ",
  //     "Resource Allocation ",
  //     "Cartonisation ",
  //     "Optimizer As A Service ",
  //     "Inbound Optimization ",
  //     "STRIDE ",
  //     "CSIS - In Home ",
  //     "CSIS - Smart Reordering ",
  //     "Walmart Mission Control ",
  //     "DCC (Distributor Carrier Configuration) ",
  //     "CONVERSATIONAL COMMERCE ",
  //     "INHOME ",
  //     "SMART REORDER ",
  //     "WELLNESS ",
  //     "NPI CORE SERVICES ",
  //   ],
  // },
];

// =================

//   pillar: "Support",
//   product: [
//     {
//       name: "Supply Chain Operations Tool (GSCOPE)",
//       applications: [
//         {
//           name: "application",
//           tools: [{ nameOfTool: "tool", toolData: ["tool information"] }],
//         },
//         {
//           name: "application",
//           tools: [{ nameOfTool: "tool", toolData: ["tool information"] }],
//         },
//         {
//           name: "application",
//           tools: [{ nameOfTool: "tool", toolData: ["tool information"] }],
//         },
//       ],
//     },
//   ],
// },
// {
